version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest # 'latest' anahtar kelimesi en son Node.js sürümünü kullanır
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync build/ s3://react-codebuild-akin --delete
